version: '3.8'

services:
  mysql-ingesta:
    build:
      context: ./mysql
    volumes:
      - ./mysql/data:/app/data
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials  # Montar el archivo de credenciales
    environment:
      MYSQL_HOST: "3.210.219.55"   # Cambia a tu host de MySQL
      MYSQL_PORT: 8005            # Cambia al puerto de MySQL
      MYSQL_USER: "root"          # Cambia a tu usuario de MySQL
      MYSQL_PASSWORD: "utec"      # Cambia a tu contraseña de MySQL
      MYSQL_DATABASE: "Aseguradora"  # Cambia a tu base de datos MySQL
      S3_BUCKET: "04c-cloud-05s03-ingesta-from-database"

  postgresql-ingesta:
    build:
      context: ./postgresql
    volumes:
      - ./postgresql/data:/app/data
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials  # Montar el archivo de credenciales
  
    environment:
      POSTGRES_HOST: "postgresql_host"  # Cambia a tu host de PostgreSQL
      POSTGRES_PORT: 5432                # Cambia al puerto de PostgreSQL
      POSTGRES_USER: "tu_usuario"        # Cambia a tu usuario de PostgreSQL
      POSTGRES_PASSWORD: "tu_contraseña"  # Cambia a tu contraseña de PostgreSQL
      POSTGRES_DB: "universidad"         # Cambia a tu base de datos PostgreSQL
      S3_BUCKET: "04c-cloud-05s03-ingesta-from-database"

  mongodb-ingesta:
    build:
      context: ./mongodb
    volumes:
      - ./mongodb/data:/app/data
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials  # Montar el archivo de credenciales
    environment:
      MONGODB_URI: "mongodb://mongo_host:27017/"  # Cambia a tu URI de MongoDB
      MONGODB_DATABASE: "universidad"              # Cambia a tu base de datos MongoDB
      S3_BUCKET: "04c-cloud-05s03-ingesta-from-database"

